Sleep and retry if assignment fails

diff --git a/.github/workflows/build-image.yaml b/.github/workflows/build-image.yaml
--- a/.github/workflows/build-image.yaml
+++ b/.github/workflows/build-image.yaml
@@ -88,9 +88,17 @@ jobs:
             sed -i -e "s%Azure Image Builder Service Image Creation Role%${IMAGE_ROLE_DEF_NAME}%g" image_creation_role.json
             cat image_creation_role.json
             az role definition create --role-definition ./image_creation_role.json
-            sleep 5  # it may show up in `az role definition list` immediately, but sometimes the assignment fails because the role "does not exist" yet
             identity_id=$(az identity list --resource-group auto-machine-images-rg | jq -r ".[] | select(.name == \"${IDENTITY_NAME}\") | .principalId")
+            set +e
+            let start=$(date '+%s')
             az role assignment create --assignee ${identity_id} --role "${IMAGE_ROLE_DEF_NAME}" --scope /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}
+            while [[ $? -ne 0 ]]
+            do
+                if [[ $(date '+%s') -gt $((start + 300)) ]]; then echo "Giving up after 5 minutes"; exit 1; fi
+                echo "Role assignment failed - trying again in 10 seconds"
+                sleep 10
+                az role assignment create --assignee ${identity_id} --role "${IMAGE_ROLE_DEF_NAME}" --scope /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}
+            done
           fi
       - name: create image template
         run: |-
